# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='userWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(choices=[(b'e', b'Self-Employed'), (b's', b'Salaried')], max_length=50)),
                ('salary', models.IntegerField(blank=True)),
                ('experience', models.IntegerField(blank=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.userInfo')),
            ],
        ),
    ]
