# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwork',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='userWork',
        ),
    ]
